const CATEGORIES = [
  { id: 1, arabic: 'بقالة / سوبرماركت', english: 'Grocery / Supermarket' },
  { id: 2, arabic: 'مخبز / معجنات', english: 'Bakery / Pastry' },
  { id: 3, arabic: 'مطعم / مقهى', english: 'Restaurant / Café' },
  { id: 4, arabic: 'وجبات سريعة', english: 'Fast Food' },
  { id: 5, arabic: 'الملابس / الأزياء', english: 'Clothing / Fashion' },
  { id: 6, arabic: 'أحذية / إكسسوارات', english: 'Shoes / Accessories' },
  { id: 7, arabic: 'إلكترونيات / أجهزة', english: 'Electronics / Appliances' },
  { id: 8, arabic: 'الجوالات / الاتصالات', english: 'Mobile / Telecom' },
  { id: 9, arabic: 'كمبيوتر وتقنية المعلومات', english: 'Computers & IT' },
  { id: 10, arabic: 'المنازل والأثاث', english: 'Home & Furniture' },
  { id: 11, arabic: 'الصحة والجمال', english: 'Health & Beauty' },
  { id: 12, arabic: 'صيدلية', english: 'Pharmacy' },
  { id: 13, arabic: 'عيادة طبية', english: 'Medical Clinic' },
  { id: 14, arabic: 'عيادة أسنان', english: 'Dental Clinic' },
  { id: 15, arabic: 'بصريات / نظارات', english: 'Optics / Eyewear' },
  { id: 16, arabic: 'حلاق / صالون جمال', english: 'Barber / Salon' },
  { id: 17, arabic: 'نادي رياضي', english: 'Gym / Fitness' },
  { id: 18, arabic: 'سفر وسياحة', english: 'Travel / Tourism' },
  {
    id: 19,
    arabic: 'إصلاح سيارات / خدمات السيارات',
    english: 'Car Repair / Auto Services',
  },
  { id: 20, arabic: 'محطة وقود', english: 'Gas Station' },
  { id: 21, arabic: 'العقارات', english: 'Real Estate' },
  {
    id: 22,
    arabic: 'كهرباء / سباكة',
    english: 'Electrical / Plumbing Services',
  },
  { id: 23, arabic: 'خدمات تنظيف', english: 'Cleaning Services' },
  { id: 24, arabic: 'توصيل / شحن', english: 'Courier / Delivery' },
  { id: 25, arabic: 'طباعة / إعلان', english: 'Printing / Advertising' },
  { id: 26, arabic: 'مكتبة / قرطاسية', english: 'Bookstore / Stationery' },
  { id: 27, arabic: 'رعاية أطفال / حضانة', english: 'Childcare / Nursery' },
  { id: 28, arabic: 'تعليم وتدريب', english: 'Education / Training' },
  { id: 29, arabic: 'تنظيم فعاليات', english: 'Event Planning' },
  {
    id: 30,
    arabic: 'تصوير فوتوغرافي / فيديو',
    english: 'Photography / Videography',
  },
  { id: 31, arabic: 'قانوني / استشارات', english: 'Legal / Consulting' },
  { id: 32, arabic: 'محاسبة / مالية', english: 'Accounting / Finance' },
  { id: 33, arabic: 'التأمين', english: 'Insurance' },
  {
    id: 34,
    arabic: 'إنشاءات / مقاولات',
    english: 'Construction / Contractors',
  },
  { id: 35, arabic: 'تنسيق حدائق', english: 'Landscaping / Gardening' },
  {
    id: 36,
    arabic: 'رعاية حيوانات / بيطري',
    english: 'Pet Care / Veterinary',
  },
  { id: 37, arabic: 'مغسلة / تنظيف جاف', english: 'Laundry / Dry Cleaning' },
  { id: 38, arabic: 'زهور / هدايا', english: 'Flowers / Gifts' },
  { id: 39, arabic: 'مجوهرات / ساعات', english: 'Jewelry / Watches' },
  { id: 40, arabic: 'مستلزمات رياضية', english: 'Sports Goods' },
  { id: 41, arabic: 'ألعاب / مستلزمات أطفال', english: 'Toys / Kids Goods' },
  { id: 42, arabic: 'أخرى (عام)', english: 'Others (General)' },
];

const CITIES = [
  { id: 1, arabic: 'الرياض', english: 'Riyadh' },
  { id: 2, arabic: 'جدة', english: 'Jeddah' },
  { id: 3, arabic: 'مكة المكرمة', english: 'Mecca' },
  { id: 4, arabic: 'المدينة المنورة', english: 'Medina' },
  { id: 5, arabic: 'الدمام', english: 'Dammam' },
  { id: 6, arabic: 'الخبر', english: 'Khobar' },
  { id: 7, arabic: 'الظهران', english: 'Dhahran' },
  { id: 8, arabic: 'بريدة', english: 'Buraydah' },
  { id: 9, arabic: 'أبها', english: 'Abha' },
  { id: 10, arabic: 'جازان', english: 'Jazan' },
  { id: 11, arabic: 'حائل', english: 'Hail' },
  { id: 12, arabic: 'تبوك', english: 'Tabuk' },
  { id: 13, arabic: 'نجران', english: 'Najran' },
  { id: 14, arabic: 'سكاكا', english: 'Sakakah' },
  { id: 15, arabic: 'الباحة', english: 'Al Bahah' },
  { id: 16, arabic: 'عرعر', english: 'Arar' },
  { id: 17, arabic: 'الطائف', english: 'Taif' },
  { id: 18, arabic: 'حفر الباطن', english: 'Hafar al-Batin' },
  { id: 19, arabic: 'الأحساء', english: 'Al-Ahsa' },
  { id: 20, arabic: 'القطيف', english: 'Qatif' },
  { id: 21, arabic: 'ينبع', english: 'Yanbu' },
  { id: 22, arabic: 'خميس مشيط', english: 'Khamis Mushait' },
  { id: 23, arabic: 'أبقيق', english: 'Abqaiq' },
  { id: 24, arabic: 'القبيرية', english: 'Al Bukiryah' },
  { id: 25, arabic: 'رابغ', english: 'Rabigh' },
  { id: 26, arabic: 'الجموم', english: 'Al Jumum' },
  { id: 27, arabic: 'الأضارع', english: "Al Ad-dari'ah" },
  { id: 28, arabic: 'صفوى', english: 'Safwa' },
  { id: 29, arabic: 'رأس تنورة', english: 'Ras Tanura' },
  { id: 30, arabic: 'الزلفي', english: 'Al Zulfi' },
  { id: 31, arabic: 'وادي الدواسر', english: 'Wadi ad-Dawasir' },
  { id: 32, arabic: 'الدوادمي', english: 'Al Dawadmi' },
  { id: 33, arabic: 'شقرا', english: 'Shaqra' },
  { id: 34, arabic: 'القويعية', english: 'Al Quwayiyah' },
  { id: 35, arabic: 'الخرج', english: 'Al Kharj' },
  { id: 36, arabic: 'الظهر', english: 'Adh Dhahr' },
  { id: 37, arabic: 'جبيل', english: 'Jubail' },
  { id: 38, arabic: 'الخفجي', english: 'Khafji' },
  { id: 39, arabic: 'بقيق', english: 'Buqayq' },
  { id: 40, arabic: 'رس', english: 'Ar Rass' },
  { id: 41, arabic: 'بيشة', english: 'Bisha' },
  { id: 42, arabic: 'ظهران الجنوب', english: 'Dhahran Al Janub' },
  { id: 43, arabic: 'النماص', english: 'An Namas' },
  { id: 44, arabic: 'محايل عسير', english: 'Muhayil Asir' },
  { id: 45, arabic: 'بلجرشي', english: 'Baljurashi' },
  { id: 46, arabic: 'تيماء', english: 'Tayma' },
  { id: 47, arabic: 'فيفا', english: 'Viva' },
  { id: 48, arabic: 'القرية العليا', english: 'Al Qurayyat' },
  { id: 49, arabic: 'ضباء', english: 'Duba' },
  { id: 50, arabic: 'الدرعية', english: 'Diriyah' },
  { id: 51, arabic: 'العلا', english: 'AlUla' },
  { id: 52, arabic: 'الشملي', english: 'Ash Shamli' },
  { id: 53, arabic: 'صبيا', english: 'Sabya' },
  { id: 54, arabic: 'النماص', english: 'An Namas' },
  { id: 55, arabic: 'الطوال', english: 'Al Tuwal' },
];

export { CATEGORIES, CITIES };
