import { useTranslation } from 'react-i18next';
import '../../styles/privacy-policy.css';

const PrivacyContentSection = () => {
  const { t, i18n } = useTranslation();

  return (
    <section
      className="privacy"
      style={{ direction: i18n.language === 'en' ? 'ltr' : 'rtl' }}
    >
      <div className="translations-content-container">
        <div className="container">
          <div className="tab-content translations-content-item">
            <h1>{t('privacyPolicyPage.content.title')}</h1>
            <p>{t('privacyPolicyPage.content.lastUpdated')}</p>
            <p>{t('privacyPolicyPage.content.introduction1')}</p>
            <p>
              {t('privacyPolicyPage.content.introduction2')}
              <a
                href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
                target="_blank"
                rel="noopener noreferrer"
              >
                TermsFeed
              </a>
              .
            </p>

            <h2>{t('privacyPolicyPage.content.interpretation.title')}</h2>
            <h3>
              {t(
                'privacyPolicyPage.content.interpretation.interpretationTitle',
              )}
            </h3>
            <p>
              {t(
                'privacyPolicyPage.content.interpretation.interpretationDescription',
              )}
            </p>
            <h3>
              {t('privacyPolicyPage.content.interpretation.definitionsTitle')}
            </h3>
            <p>
              {t(
                'privacyPolicyPage.content.interpretation.definitionsDescription',
              )}
            </p>
            <ul>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.account')}</p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.affiliate')}</p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.company')}</p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.cookies')}</p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.country')}</p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.device')}</p>
              </li>
              <li>
                <p>
                  {t('privacyPolicyPage.content.interpretation.personalData')}
                </p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.service')}</p>
              </li>
              <li>
                <p>
                  {t(
                    'privacyPolicyPage.content.interpretation.serviceProvider',
                  )}
                </p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.usageData')}</p>
              </li>
              <li>
                <p>
                  {t('privacyPolicyPage.content.interpretation.website')}{' '}
                  <a
                    href="https://www.debtbox.sa/"
                    rel="external nofollow noopener"
                    target="_blank"
                  >
                    https://www.debtbox.sa/
                  </a>
                </p>
              </li>
              <li>
                <p>{t('privacyPolicyPage.content.interpretation.you')}</p>
              </li>
            </ul>

            <h2>{t('privacyPolicyPage.content.collectingData.title')}</h2>
            <h3>{t('privacyPolicyPage.content.collectingData.typesTitle')}</h3>
            <h4>
              {t('privacyPolicyPage.content.collectingData.personalDataTitle')}
            </h4>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.personalDataDescription',
              )}
            </p>
            <ul>
              <li>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.personalDataList1',
                  )}
                </p>
              </li>
              <li>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.personalDataList2',
                  )}
                </p>
              </li>
              <li>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.personalDataList3',
                  )}
                </p>
              </li>
              <li>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.personalDataList4',
                  )}
                </p>
              </li>
            </ul>

            <h4>
              {t('privacyPolicyPage.content.collectingData.usageDataTitle')}
            </h4>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.usageDataDescription1',
              )}
            </p>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.usageDataDescription2',
              )}
            </p>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.usageDataDescription3',
              )}
            </p>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.usageDataDescription4',
              )}
            </p>

            <h4>
              {t('privacyPolicyPage.content.collectingData.trackingTitle')}
            </h4>
            <p>
              {t(
                'privacyPolicyPage.content.collectingData.trackingDescription',
              )}
            </p>
            <ul>
              <li>
                <p>
                  {t('privacyPolicyPage.content.collectingData.cookiesBrowser')}
                </p>
              </li>
              <li>
                <p>
                  {t('privacyPolicyPage.content.collectingData.webBeacons')}
                </p>
              </li>
            </ul>
            <p>
              {t('privacyPolicyPage.content.collectingData.cookiesTypes')}
              <a
                href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
                target="_blank"
                rel="noopener noreferrer"
              >
                TermsFeed
              </a>
              .
            </p>
            <p>{t('privacyPolicyPage.content.collectingData.cookiesUsage')}</p>
            <ul>
              <li>
                <p>
                  <strong>
                    {t(
                      'privacyPolicyPage.content.collectingData.necessaryCookies.title',
                    )}
                  </strong>
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.necessaryCookies.type',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.necessaryCookies.administered',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.necessaryCookies.purpose',
                  )}
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t(
                      'privacyPolicyPage.content.collectingData.policyCookies.title',
                    )}
                  </strong>
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.policyCookies.type',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.policyCookies.administered',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.policyCookies.purpose',
                  )}
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t(
                      'privacyPolicyPage.content.collectingData.functionalityCookies.title',
                    )}
                  </strong>
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.functionalityCookies.type',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.functionalityCookies.administered',
                  )}
                </p>
                <p>
                  {t(
                    'privacyPolicyPage.content.collectingData.functionalityCookies.purpose',
                  )}
                </p>
              </li>
            </ul>
            <p>{t('privacyPolicyPage.content.collectingData.moreInfo')}</p>

            <h3>{t('privacyPolicyPage.content.useOfData.title')}</h3>
            <p>{t('privacyPolicyPage.content.useOfData.description')}</p>
            <ul>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.provideService')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.manageAccount')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.contract')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.contact')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.provideNews')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.manageRequests')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.businessTransfers')}
                  </strong>
                </p>
              </li>
              <li>
                <p>
                  <strong>
                    {t('privacyPolicyPage.content.useOfData.otherPurposes')}
                  </strong>
                </p>
              </li>
            </ul>
            <p>{t('privacyPolicyPage.content.useOfData.sharingDescription')}</p>
            <ul>
              <li>
                <strong>
                  {t('privacyPolicyPage.content.useOfData.serviceProviders')}
                </strong>
              </li>
              <li>
                <strong>
                  {t(
                    'privacyPolicyPage.content.useOfData.businessTransfersSharing',
                  )}
                </strong>
              </li>
              <li>
                <strong>
                  {t('privacyPolicyPage.content.useOfData.affiliates')}
                </strong>
              </li>
              <li>
                <strong>
                  {t('privacyPolicyPage.content.useOfData.businessPartners')}
                </strong>
              </li>
              <li>
                <strong>
                  {t('privacyPolicyPage.content.useOfData.otherUsers')}
                </strong>
              </li>
              <li>
                <strong>
                  {t('privacyPolicyPage.content.useOfData.withConsent')}
                </strong>
              </li>
            </ul>

            <h3>{t('privacyPolicyPage.content.retention.title')}</h3>
            <p>{t('privacyPolicyPage.content.retention.description1')}</p>
            <p>{t('privacyPolicyPage.content.retention.description2')}</p>

            <h3>{t('privacyPolicyPage.content.transfer.title')}</h3>
            <p>{t('privacyPolicyPage.content.transfer.description1')}</p>
            <p>{t('privacyPolicyPage.content.transfer.description2')}</p>
            <p>{t('privacyPolicyPage.content.transfer.description3')}</p>

            <h3>{t('privacyPolicyPage.content.delete.title')}</h3>
            <p>{t('privacyPolicyPage.content.delete.description1')}</p>
            <p>{t('privacyPolicyPage.content.delete.description2')}</p>
            <p>{t('privacyPolicyPage.content.delete.description3')}</p>
            <p>{t('privacyPolicyPage.content.delete.description4')}</p>

            <h3>{t('privacyPolicyPage.content.disclosure.title')}</h3>
            <h4>
              {t(
                'privacyPolicyPage.content.disclosure.businessTransactions.title',
              )}
            </h4>
            <p>
              {t(
                'privacyPolicyPage.content.disclosure.businessTransactions.description',
              )}
            </p>
            <h4>
              {t('privacyPolicyPage.content.disclosure.lawEnforcement.title')}
            </h4>
            <p>
              {t(
                'privacyPolicyPage.content.disclosure.lawEnforcement.description',
              )}
            </p>
            <h4>
              {t('privacyPolicyPage.content.disclosure.otherLegal.title')}
            </h4>
            <p>
              {t('privacyPolicyPage.content.disclosure.otherLegal.description')}
            </p>
            <ul>
              <li>
                {t('privacyPolicyPage.content.disclosure.otherLegal.list1')}
              </li>
              <li>
                {t('privacyPolicyPage.content.disclosure.otherLegal.list2')}
              </li>
              <li>
                {t('privacyPolicyPage.content.disclosure.otherLegal.list3')}
              </li>
              <li>
                {t('privacyPolicyPage.content.disclosure.otherLegal.list4')}
              </li>
              <li>
                {t('privacyPolicyPage.content.disclosure.otherLegal.list5')}
              </li>
            </ul>

            <h3>{t('privacyPolicyPage.content.security.title')}</h3>
            <p>{t('privacyPolicyPage.content.security.description')}</p>

            <h2>{t('privacyPolicyPage.content.childrenPrivacy.title')}</h2>
            <p>{t('privacyPolicyPage.content.childrenPrivacy.description1')}</p>
            <p>{t('privacyPolicyPage.content.childrenPrivacy.description2')}</p>

            <h2>{t('privacyPolicyPage.content.links.title')}</h2>
            <p>{t('privacyPolicyPage.content.links.description1')}</p>
            <p>{t('privacyPolicyPage.content.links.description2')}</p>

            <h2>{t('privacyPolicyPage.content.changes.title')}</h2>
            <p>{t('privacyPolicyPage.content.changes.description1')}</p>
            <p>{t('privacyPolicyPage.content.changes.description2')}</p>
            <p>{t('privacyPolicyPage.content.changes.description3')}</p>

            <h2>{t('privacyPolicyPage.content.contact.title')}</h2>
            <p>{t('privacyPolicyPage.content.contact.description')}</p>
            <ul>
              <li>
                {t('privacyPolicyPage.content.contact.byVisiting')}
                <a
                  href="https://www.debtbox.sa/"
                  rel="external nofollow noopener"
                  target="_blank"
                >
                  https://www.debtbox.sa/
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
};

export default PrivacyContentSection;
